* Edward Kmett
+ https://www.cs.drexel.edu/~mainland/publications/mainland10nikola.pdf function application
+ http://www.cs.uu.nl/wiki/pub/Afp/CourseLiterature/Gill-09-TypeSafeReification.pdf
+ http://hackage.haskell.org/package/ersatz
+ http://stackoverflow.com/questions/1023981/practical-applications-of-homomorphic-encryption-algorithms/1045844#1045844
+ http://stackoverflow.com/questions/11694997/how-to-reify-a-list-of-data-using-data-reify
* Maxeler Course
There are 2 hotels we use quite a lot which are within 5mins walk of the office:
1) Novotel London West 4Star, from 119GBP per night,
http://www.novotel.com/gb/hotel-0737-novotel-london-west/index.shtml

2)  Best Western Seraphine Hammersmith 3Star, from 95GBP per night,
http://www.seraphinehotel.co.uk/hammersmith/

A bit further away (10min bus ride to the office), in zone 1 but still
on the west side in Kensington there are:

1) Baglioni Hotel 5 Star from 215GBP per night,
http://www.baglionihotels.com/en/destinations/london/baglioni-hotel/hotel

2) Kensington House 4 Star from 108GBP per night,
http://www.kenhouse.com/index.html

3) Copthorne Tara Hotel 4Star from 150GBP per night,
http://www.millenniumhotels.co.uk/copthornetarakensington

Course at '1 Down Place' about Maxeler tools and hardware that takes place on 8-9 April. 
Projects which involve FPGA synthesis. 


The Best Western Seraphine Hammersmith looks good (and is also very cheap), I also found another hotel http://www.adria-hotel.co.uk/hotel-overview.html which seems to offer as low as £62-89 a nigh but really any hotel is fine with me so I guess it depends on if we can find a cheaper one or if Xia and everyone is fine with these.

Where is the FP group meeting today by the way? Is it in the group room on the top floor?

Here is the new github account with meh implementation of somewhat homomorphic encryption, https://github.com/Icelandjack/FHE/


* Kansa Lava
https://github.com/ku-fpg

https://github.com/ku-fpg/kansas-lava-cores
https://github.com/ku-fpg/kansas-lava
https://github.com/ku-fpg/lambda-ccc
* Conference
** Mary
This might be a good place to report work in progress on the masters project.

I went to this conference a few years ago (as invited speaker) and had a great time.

M
** Conference
CALL FOR PAPERS

18th Brazilian Symposium on Programming Languages (SBLP 2014)

A member of CBSoft joint conference
http://www.ic.ufal.br/evento/cbsoft2014/
to be held in Maceio, Brazil.

SBLP happens on Thursday, Oct 2nd, and Friday, Oct 3rd.
CBSoft dates are September 28, 2014 to October 3, 2014


IMPORTANT DATES

Paper abstract submission: May 2nd, 2014
Full paper submission: May 9th, 2014
Notification of acceptance: June 13th, 2014
Final papers due: July 4th, 2014

* DONE Implement SHE in Haskell
  CLOSED: [2014-03-16 Sun 10:58]
* TODO Implement FHE in Haskell
* TODO Run C++ library
* TODO Read paper on FHE optimizations
* TODO Start paper
** TODO Related work
** TODO Preliminary implementation
** TODO Preliminary implementation
* TODO Project Description

I think that the project description should be written more to be
readable by the average computer scientist who doesn't know functional
programming (and in particular the masters thesis coordinator :) so
please put in a bit more background and explanation.  I am not sure
what is meant by "tuned to run in parallel" here (and I think what you
probably mean is subsumed by the trading time and space that comes
immediately after).

It would probably be good to put in something about implementing components that support fully homomorphic encryption (rather than promising
the whole thing). It is good to have a backup plan (probably involving other crypto algos) if the main aim turns out to be just too hard. (You seem to be thinking along these lines in your plan). I am inclined to mention it even in the project description.

Say something about how success of the project will be evaluated (e.g. by comparison with Cryptol).

I think you should add that the project is research oriented and is intended to result in a publication.

The project plan looks good to me.

I remembered another piece of related work: spiral in Scala.
http://spiral.ece.cmu.edu:8080/pub-spiral/pubfile/paper_170.pdf
Here, they seem to be talking about Spiral for software generation, but they have also generated hardware, I believe.
And I guess the original spiral.org page is interesting to see their work on hardware synthesis.

And there is another paper by the same Scala crowd:
http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=6718341
though I can't look at it until Chalmers library puts search back.

I have still not had a chance to look at the work you found. Soon!



-----

Yes, put in something a bit vague about verification -- along the lines of :   We will investigate the possibility of including a limited form of property based testing or formal verification in the DSL.

Yes, if playing with time and space is going to be the game, doing something about that in the types seems like a good thing to investigate.

I just got some funding from ENS for the French student for the trip to London, so you will be two on the course. This is probably good for working on a small project together, comparing notes etc.  I am hoping that you can survive flying Ryanair. I just checked their fares and they are very good. I will have to find out how to correctly pay for the tickets (to obey tax and Chalmers rules).



